[tool.poetry]
name = "lookyloo-tutorial"
version = "0.1.0"
description = "A developer-oriented tutorial to understand what lookyloo is for"
authors = ["RaphaÃ«l Vinot <raphael@lookyloo.eu>"]

[tool.poetry.dependencies]
python = "^3.8"
jupyterlab = "^2.2.8"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
